// Auto-generated. Do not edit!

// (in-package ros_start.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GoUntilBumperFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_vel = null;
    }
    else {
      if (initObj.hasOwnProperty('current_vel')) {
        this.current_vel = initObj.current_vel
      }
      else {
        this.current_vel = new geometry_msgs.msg.Twist();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GoUntilBumperFeedback
    // Serialize message field [current_vel]
    bufferOffset = geometry_msgs.msg.Twist.serialize(obj.current_vel, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GoUntilBumperFeedback
    let len;
    let data = new GoUntilBumperFeedback(null);
    // Deserialize message field [current_vel]
    data.current_vel = geometry_msgs.msg.Twist.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 48;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_start/GoUntilBumperFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3186359c02aecabea670ec7a240a2497';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/Twist current_vel
    
    
    ================================================================================
    MSG: geometry_msgs/Twist
    # This expresses velocity in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GoUntilBumperFeedback(null);
    if (msg.current_vel !== undefined) {
      resolved.current_vel = geometry_msgs.msg.Twist.Resolve(msg.current_vel)
    }
    else {
      resolved.current_vel = new geometry_msgs.msg.Twist()
    }

    return resolved;
    }
};

module.exports = GoUntilBumperFeedback;
