// Generated by gencpp from file ros_start/Setvelocity.msg
// DO NOT EDIT!


#ifndef ROS_START_MESSAGE_SETVELOCITY_H
#define ROS_START_MESSAGE_SETVELOCITY_H

#include <ros/service_traits.h>


#include <ros_start/SetvelocityRequest.h>
#include <ros_start/SetvelocityResponse.h>


namespace ros_start
{

struct Setvelocity
{

typedef SetvelocityRequest Request;
typedef SetvelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Setvelocity
} // namespace ros_start


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_start::Setvelocity > {
  static const char* value()
  {
    return "f6aaad2e58fe90e46753c2e927c41798";
  }

  static const char* value(const ::ros_start::Setvelocity&) { return value(); }
};

template<>
struct DataType< ::ros_start::Setvelocity > {
  static const char* value()
  {
    return "ros_start/Setvelocity";
  }

  static const char* value(const ::ros_start::Setvelocity&) { return value(); }
};


// service_traits::MD5Sum< ::ros_start::SetvelocityRequest> should match 
// service_traits::MD5Sum< ::ros_start::Setvelocity > 
template<>
struct MD5Sum< ::ros_start::SetvelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start::Setvelocity >::value();
  }
  static const char* value(const ::ros_start::SetvelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start::SetvelocityRequest> should match 
// service_traits::DataType< ::ros_start::Setvelocity > 
template<>
struct DataType< ::ros_start::SetvelocityRequest>
{
  static const char* value()
  {
    return DataType< ::ros_start::Setvelocity >::value();
  }
  static const char* value(const ::ros_start::SetvelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_start::SetvelocityResponse> should match 
// service_traits::MD5Sum< ::ros_start::Setvelocity > 
template<>
struct MD5Sum< ::ros_start::SetvelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_start::Setvelocity >::value();
  }
  static const char* value(const ::ros_start::SetvelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_start::SetvelocityResponse> should match 
// service_traits::DataType< ::ros_start::Setvelocity > 
template<>
struct DataType< ::ros_start::SetvelocityResponse>
{
  static const char* value()
  {
    return DataType< ::ros_start::Setvelocity >::value();
  }
  static const char* value(const ::ros_start::SetvelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_START_MESSAGE_SETVELOCITY_H
