// Auto-generated. Do not edit!

// (in-package ros_start.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class GoUntilBumperResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.bumper_hit = null;
    }
    else {
      if (initObj.hasOwnProperty('bumper_hit')) {
        this.bumper_hit = initObj.bumper_hit
      }
      else {
        this.bumper_hit = false;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GoUntilBumperResult
    // Serialize message field [bumper_hit]
    bufferOffset = _serializer.bool(obj.bumper_hit, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GoUntilBumperResult
    let len;
    let data = new GoUntilBumperResult(null);
    // Deserialize message field [bumper_hit]
    data.bumper_hit = _deserializer.bool(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_start/GoUntilBumperResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1ee6f808d38c7963a5003e418bc90ac6';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    bool bumper_hit
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GoUntilBumperResult(null);
    if (msg.bumper_hit !== undefined) {
      resolved.bumper_hit = msg.bumper_hit;
    }
    else {
      resolved.bumper_hit = false
    }

    return resolved;
    }
};

module.exports = GoUntilBumperResult;
