// Auto-generated. Do not edit!

// (in-package ros_start.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class GoUntilBumperGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.target_vel = null;
      this.timeout_sec = null;
    }
    else {
      if (initObj.hasOwnProperty('target_vel')) {
        this.target_vel = initObj.target_vel
      }
      else {
        this.target_vel = new geometry_msgs.msg.Twist();
      }
      if (initObj.hasOwnProperty('timeout_sec')) {
        this.timeout_sec = initObj.timeout_sec
      }
      else {
        this.timeout_sec = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GoUntilBumperGoal
    // Serialize message field [target_vel]
    bufferOffset = geometry_msgs.msg.Twist.serialize(obj.target_vel, buffer, bufferOffset);
    // Serialize message field [timeout_sec]
    bufferOffset = _serializer.int32(obj.timeout_sec, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GoUntilBumperGoal
    let len;
    let data = new GoUntilBumperGoal(null);
    // Deserialize message field [target_vel]
    data.target_vel = geometry_msgs.msg.Twist.deserialize(buffer, bufferOffset);
    // Deserialize message field [timeout_sec]
    data.timeout_sec = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 52;
  }

  static datatype() {
    // Returns string type for a message object
    return 'ros_start/GoUntilBumperGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c9b5f8f2aced60d6e82fa76ca79b621a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/Twist target_vel
    int32 timeout_sec
    
    ================================================================================
    MSG: geometry_msgs/Twist
    # This expresses velocity in free space broken into its linear and angular parts.
    Vector3  linear
    Vector3  angular
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GoUntilBumperGoal(null);
    if (msg.target_vel !== undefined) {
      resolved.target_vel = geometry_msgs.msg.Twist.Resolve(msg.target_vel)
    }
    else {
      resolved.target_vel = new geometry_msgs.msg.Twist()
    }

    if (msg.timeout_sec !== undefined) {
      resolved.timeout_sec = msg.timeout_sec;
    }
    else {
      resolved.timeout_sec = 0
    }

    return resolved;
    }
};

module.exports = GoUntilBumperGoal;
